### ISSUE TITLE
Rate Limits

### ISSUE THREAD

**Issue by Schins02** [tungoo7/BevoMaps#1]
Parse 30 req/s
>>> 30 * 60
1800
>>> 1800 * 60
108000
>>> 108000 * 24
2592000  per Day

Imugr
The Imgur API uses a credit allocation system to ensure fair distribution of capacity. Each application can allow approximately 1,250 uploads per day or approximately 12,500 requests per day.

If you find you're being rate limited, and your app is completely free (and without ads), then you can submit a request to be white-listed. We ask that you simply fill out this form and we'll let you know if you qualify.

Google App Engine
Resource	Free Default Limit	Billing Enabled Default Limit
Daily Limit	Maximum Rate	Daily Limit	Maximum Rate
Channel API Calls	657,000 calls	3,000 calls/minute	91,995,495 calls	32,000 calls/minute

**Comment by Schins02** [comment]
Cache or persist some of the most popular buildings/floor-plans to reduce potential rate limit problems

**Comment by tungoo7** [comment]
Per-second rate limit most relevant due peaky network access. Can store a floor-->URL mapping in Parse, and store images on Imgur. No Imgur API required; need only GET requests, no known limit. Cache most recently use floors, else concurrently load all floors of selected building.
